apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-web-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"    # REQUIRED for HPA to work
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "25Mi"



